let canvas = document.getElementById("game");
let ctx = canvas.getContext("2d");
let currentLevel = {};
let mapWidth;
let mousePos = {};
let keyState = [];
let playerX;
let playerY;
let playerYSpeed = 0;
let playerXSpeed = .2;
let almostOne = .999;
let moveLeft;
let moveRight;
let gravity = .028;
let titleScreen = false;
let levelSelectScreen = false;
let gameScreen = false;
let paused = false;
let defaultLevels = ["SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSLLSSSSSLLSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSGSSS\
SSSCSCSCSSSSSSCSSSSSSSSGSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSC\
EPSCSCSCSSGGGSSSGGGSSSSSSSSSSS\
EPSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
GGGGGGGGGGLLLLLLLLLGGGGGGGGGLL","SCSSSSCSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSS\
SGSSSSGSSGSSSSSSSSSS\
SSSSCSGLLLLLGSSSSSSS\
SSGSSSGGGGGGGGSSSCSS\
SSSSSSSSSSSSSGGGSSSS\
SSSSGSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSGGSS\
SSSSSSGLLGSSSSSSSSSS\
SSSSSSGGGGGSSGSSSSSG\
SSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSGLGS\
SSSSSSSSSSSSSGGSGGGS\
SSSSSSSSSSSSSSSSSSSS\
SSSSSCSSSSSGSSSSSSSS\
SSSSSSSSGGSSSGGSSSSS\
SPSSGGGSSSSSSSSSGSES\
SPSSSSSSSSSSSSSSSSES\
GGGLLLLLLLLLLLLLLGGG\
GGGGGGGGGGGGGGGGGGGG","SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSCSSSSSSSSSS\
CSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGSSSSSSSSS\
SGGGGGGSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGSSSSS\
SSSSSSSSSSCSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSGSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSGGGGGGSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGSSSS\
SSSSSSSSSSSSSSGSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGGSSSSSS\
SSSSSSSSSSSSSSSGSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGSSSSSSSSSS\
SESSSSSSSSSSSSSSSGGSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSGSSSSPSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSPSSSSSSSSSSSSSSSSSSSSSSSS\
LLLLLLLLLLLLLLLLLLLLGGGGGGGGGLLLLGGGGGGGGGGGGGGGGG\
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG\
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG\
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"];
let ground = [];
let coin = [];
let player = [];
let lava = [];
let exit = [];
let lightBlue = "#72a8ff";
let brown = "#634c3d";
let yellow = "#f2f241";
let red = "#d11717";
let green = "#28aa11";
let orange = "#ea9525";