let canvas = document.getElementById("game");
let ctx = canvas.getContext("2d");
let currentLevel = {};
let mapWidth;
let mousePos = {};
let titleScreen = false;
let levelSelectScreen = false;
let defaultLevels = ["SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSLLSSSSSLLSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSCSCSCSSSSSSCSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSC\
EPSCSCSCSSGGGSSSGGGSSSSSSSSSSS\
EPSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
GGGGGGGGGGLLLLLLLLLGGGGGGGGGLL","","SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSCSSSSSSSSSS\
CSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGSSSSSSSSS\
SGGGGGGSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGSSSSS\
SSSSSSSSSSCSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSGSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSGGGGGGSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGSSSS\
SSSSSSSSSSSSSSGSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGGSSSSSS\
SSSSSSSSSSSSSSSGSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGSSSSSSSSSS\
SESSSSSSSSSSSSSSSGGSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGGSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSGSSSSPSSSSSSSSSSSSSSSSSSSSSSSS\
SSSSSSSSSSSSSSSSSSSSSSSSSPSSSSSSSSSSSSSSSSSSSSSSSS\
LLLLLLLLLLLLLLLLLLLLGGGGGGGGGLLLLGGGGGGGGGGGGGGGGG\
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG\
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG\
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"];
let ground = [];
let coin = [];
let player = [];
let lava = [];
let exit = [];
let lightBlue = "#72a8ff";
let brown = "#634c3d";
let yellow = "#f2f241";
let red = "#d11717";
let green = "#28aa11";
let orange = "#ea9525";


